### ISSUE TITLE
Runtime Issue

### ISSUE THREAD

**Issue by Brijendrasial** [kyungw00k/ads-finder#6]
Hello,

I am getting below error. Can you check it.

root@b [~]# /root/node_modules/.bin/adsFinder  poppinmedia.com

/root/node_modules/ads-finder/cli.js:23
const cli = meow(`
                 ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by kyungw00k** [comment]
I think you should update the version of node which can use the `template literal` feature.
(See https://node.green/)
